---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# trafikanalysR

<!-- badges: start -->
<!-- badges: end -->

- The goal of trafikanalysR is to make Trafikanalys' API (http://api.trafa.se/api/data?query=) more accessible. 

- API documentation: https://www.trafa.se/sidor/api-dokumentation/  

- Trafikanalys' page: https://www.trafa.se/


## Installation


Development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("JohanSalomonssonSV/trafikanalysR")
```
## Example

Getting variables in each of the data combinations in data table *bussarT10011*:

```{r}
library(trafikanalysR)

ow_bussarT10011("http://api.trafa.se/api/data?query=")



```

Plotting data combinations and variable availability within each set:

```{r}
ow_plot(ow_bussarT10011("http://api.trafa.se/api/data?query="))
```

Fetching Data 1 in *bussarT10011*:

```{r}
fetch_bussarT10011("http://api.trafa.se/api/data?query=", 1)
```

