#' @title ow_plot_filter
#' @importFrom magrittr "%>%"
#' @importFrom dplyr mutate filter distinct
#' @param df a df generated by ow_* function
#' @param VAR a Variable to filter for
#' @export


ow_plot_filter<-function(df, VAR){
  data_with_variable<-df %>%
  filter(Name==VAR) %>%
    distinct(DATA, .keep_all=TRUE) %>% .$DATA

  df %>%
    filter(DATA %in% data_with_variable) %>%
    ow_plot(.)
}
